version: "3.8"
services:
  blog-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blog
    container_name: blog-db
    expose:
      - 5432:5432
  blog-go:
    build:
      context: ./go
    container_name: blog-go
    environment:
      PORT: 8080
      DB_ADDR: postgresql://root:secret@blog-db/blog?sslmode=disable
    expose:
      - 8080:8080
    depends_on:
      - blog-db
    volumes:
      - ./go/:/app
  blog-deno:
    build:
      context: ./deno
    container_name: blog-deno
    environment:
      PORT: 8081
      GO_SERVICE_URL: http://blog-go:8080
    ports:
      - 8081:8081
    volumes:
      - ./deno/:/app
  blog-client:
    build:
      context: ./client
    container_name: blog-client
    ports:
      - 5173:5173
    volumes:
      - ./client/:/app
